# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NudgeNudge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NudgeNudge

  target 'NudgeNudge-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSound', :path => '../node_modules/react-native-sound'

  end

  target 'NudgeNudgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'